### ISSUE TITLE
Missing dist-info breaks project

### ISSUE THREAD

**Issue by MarcelWilson** [ScreenPyHQ/screenpy_selenium#17]
readthedocs build is failing.  

```
[rtd-command-info] start-time: 2022-10-19T16:46:37.509377Z, end-time: 2022-10-19T16:46:37.933083Z, duration: 0, exit-code: 2
/home/docs/checkouts/readthedocs.org/user_builds/screenpy-selenium-docs/envs/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/screenpy-selenium-docs/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/screenpy-selenium-docs/checkouts/latest/docs/conf.py", line 20, in <module>
    from screenpy_selenium.__version__ import __version__, __author__, __copyright__  # noqa: need the path first
  File "/home/docs/checkouts/readthedocs.org/user_builds/screenpy-selenium-docs/checkouts/latest/screenpy_selenium/__version__.py", line 13, in <module>
    metadata = importlib_metadata.metadata("screenpy_selenium")
  File "/home/docs/.asdf/installs/python/3.10.4/lib/python3.10/importlib/metadata/__init__.py", line 974, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/home/docs/.asdf/installs/python/3.10.4/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for screenpy_selenium
```

**Comment by MarcelWilson** [comment]
It would appear that the build does not utilize pip to install the screenpy_selenium package itself.  As a result, no dist-info is created for `importlib.metadata.metadata` to read which is how the `__version__.py` file produces the proper version values.

**Comment by bandophahita** [comment]
If I understand it correctly, we should be able to put `-e .` in the rtd-requirements.txt.
